services:
  microgrid:
    build: .
    network_mode: "host"
    ports:
      - "5001:5001"
    depends_on:
      - evcc
    volumes:
      - ./evcc-data/evcc.yaml:/etc/evcc.yaml
      - ./MicroGrid.db:/app/MicroGrid.db  # Mount database file
    environment:
      - DATABASE_FILE=/app/MicroGrid.db  # Set environment variable for Flask
  evcc:
    image: evcc/evcc:latest
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ./evcc-data/evcc.yaml:/etc/evcc.yaml
      - ./evcc-data/data:/root/.evcc
    ports:
      - "7070:7070"  # Adjust the port as needed
    environment:
      - TZ=Europe/Athens